@startuml

actor Client
participant "API Gateway" as APIGateway
participant RemoveBookFromCatalogActivity
participant RemoveBookFromCatalogRequest
participant CatalogDao
participant RemoveBookFromCatalogResponse
database DynamoDB


Client -> APIGateway : DELETE
activate Client
APIGateway -> RemoveBookFromCatalogActivity : execute(RemoveBookFromCatalogRequest)
RemoveBookFromCatalogActivity -> CatalogDao: RemoveBookFromCatalogResponse
CatalogDao -> DynamoDB : removeBookFromCatalog

alt if book not found by ID
    CatalogDao <-- DynamoDB : BookNotFoundException


@enduml